sudo: required
services:
  - docker

before_install:
  - docker build -t dcoy/super-simple-docker-react -f Dockerfile.dev .

script:
  - docker run dcoy/super-simple-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-906512401701'
  bucket_path: 'docker-react'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_ACCESS_KEY'
  on:
    branch: master
